### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by summerinsects** [ZHOURUIH/Mahjong_Server#1]
\mahjong_server-master\server\frame\common\serverdefine.h(65): fatal error C1083: Cannot open include file: 'mysql.h': No such file or directory

**Comment by ZHOURUIH** [comment]
你安装一下mysql,然后再配置一下,目前用户名和密码都是在代码里固定的,你可以在代码中自己修改

**Comment by summerinsects** [comment]
ok
